# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.0].define(version: 2022_03_22_203601) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "articles", force: :cascade do |t|
    t.text "body"
    t.string "title"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "events", force: :cascade do |t|
    t.string "band_area"
    t.string "producer"
    t.string "primary_contact_first_name"
    t.string "primary_contact_last_name"
    t.string "primary_contact_email"
    t.string "primary_contact_phone"
    t.string "primary_contact_address1"
    t.string "primary_contact_address2"
    t.string "primary_contact_city"
    t.string "primary_contact_state"
    t.string "primary_contact_zip"
    t.string "primary_contact_country"
    t.string "primary_contact_role"
    t.string "secondary_contact_first_name"
    t.string "secondary_contact_last_name"
    t.string "secondary_contact_email"
    t.string "secondary_contact_phone"
    t.string "secondary_contact_address1"
    t.string "secondary_contact_address2"
    t.string "secondary_contact_city"
    t.string "secondary_contact_state"
    t.string "secondary_contact_zip"
    t.string "secondary_contact_country"
    t.string "secondary_contact_role"
    t.string "tertiary_contact_first_name"
    t.string "tertiary_contact_last_name"
    t.string "tertiary_contact_email"
    t.string "tertiary_contact_phone"
    t.string "tertiary_contact_address1"
    t.string "tertiary_contact_address2"
    t.string "tertiary_contact_city"
    t.string "tertiary_contact_state"
    t.string "tertiary_contact_zip"
    t.string "tertiary_contact_country"
    t.string "tertiary_contact_role"
    t.datetime "event_date"
    t.string "event_type"
    t.string "event_status"
    t.string "event_guest_count"
    t.text "event_schedule"
    t.string "event_load_in_time"
    t.string "event_soundcheck_time_start"
    t.string "event_soundcheck_time_end"
    t.string "event_start_time"
    t.string "set_1_start_time"
    t.string "set_1_end_time"
    t.string "set_2_start_time"
    t.string "set_2_end_time"
    t.string "set_3_start_time"
    t.string "set_3_end_time"
    t.string "set_4_start_time"
    t.string "set_4_end_time"
    t.string "event_end_time"
    t.string "venue_name"
    t.string "venue_phone"
    t.string "venue_email"
    t.string "venue_website"
    t.string "venue_address1"
    t.string "venue_address2"
    t.string "venue_city"
    t.string "venue_state"
    t.string "venue_zip"
    t.string "venue_country"
    t.string "band_size"
    t.string "band_attire"
    t.string "musician_01"
    t.string "musician_02"
    t.string "musician_03"
    t.string "musician_04"
    t.string "musician_05"
    t.string "musician_06"
    t.string "musician_07"
    t.string "musician_08"
    t.string "musician_09"
    t.string "musician_10"
    t.string "musician_11"
    t.string "musician_12"
    t.string "musician_13"
    t.string "musician_14"
    t.string "musician_15"
    t.string "musician_16"
    t.string "musician_17"
    t.string "musician_18"
    t.string "musician_19"
    t.string "musician_20"
    t.string "musician_01_pay_rate"
    t.string "musician_02_pay_rate"
    t.string "musician_03_pay_rate"
    t.string "musician_04_pay_rate"
    t.string "musician_05_pay_rate"
    t.string "musician_06_pay_rate"
    t.string "musician_07_pay_rate"
    t.string "musician_08_pay_rate"
    t.string "musician_09_pay_rate"
    t.string "musician_10_pay_rate"
    t.string "musician_11_pay_rate"
    t.string "musician_12_pay_rate"
    t.string "musician_13_pay_rate"
    t.string "musician_14_pay_rate"
    t.string "musician_15_pay_rate"
    t.string "musician_16_pay_rate"
    t.string "musician_17_pay_rate"
    t.string "musician_18_pay_rate"
    t.string "musician_19_pay_rate"
    t.string "musician_20_pay_rate"
    t.string "musician_01_invited"
    t.string "musician_02_invited"
    t.string "musician_03_invited"
    t.string "musician_04_invited"
    t.string "musician_05_invited"
    t.string "musician_06_invited"
    t.string "musician_07_invited"
    t.string "musician_08_invited"
    t.string "musician_09_invited"
    t.string "musician_10_invited"
    t.string "musician_11_invited"
    t.string "musician_12_invited"
    t.string "musician_13_invited"
    t.string "musician_14_invited"
    t.string "musician_15_invited"
    t.string "musician_16_invited"
    t.string "musician_17_invited"
    t.string "musician_18_invited"
    t.string "musician_19_invited"
    t.string "musician_20_invited"
    t.string "musician_01_accepted"
    t.string "musician_02_accepted"
    t.string "musician_03_accepted"
    t.string "musician_04_accepted"
    t.string "musician_05_accepted"
    t.string "musician_06_accepted"
    t.string "musician_07_accepted"
    t.string "musician_08_accepted"
    t.string "musician_09_accepted"
    t.string "musician_10_accepted"
    t.string "musician_11_accepted"
    t.string "musician_12_accepted"
    t.string "musician_13_accepted"
    t.string "musician_14_accepted"
    t.string "musician_15_accepted"
    t.string "musician_16_accepted"
    t.string "musician_17_accepted"
    t.string "musician_18_accepted"
    t.string "musician_19_accepted"
    t.string "musician_20_accepted"
    t.text "client_notes"
    t.text "special_requests"
    t.text "staff_notes"
    t.text "finances_formal_quote"
    t.string "finances_total_price"
    t.string "finances_commission1"
    t.string "finances_commission2"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id"
    t.index ["user_id"], name: "index_events_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "band_area_1"
    t.string "band_area_2"
    t.string "band_area_3"
    t.string "band_area_4"
    t.string "band_area_5"
    t.string "band_area_6"
    t.string "band_area_7"
    t.string "band_area_8"
    t.string "band_area_9"
    t.string "preferred_first_name"
    t.string "preferred_last_name"
    t.string "nick_name"
    t.string "email"
    t.string "phone"
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.string "state"
    t.string "zip"
    t.string "country"
    t.string "password_digest"
    t.string "staff_rating"
    t.text "staff_notes"
    t.string "tax_first_name"
    t.string "tax_last_name"
    t.string "tax_address1"
    t.string "tax_address2"
    t.string "tax_city"
    t.string "tax_state"
    t.string "tax_zip"
    t.string "tax_country"
    t.string "tax_id_number"
    t.string "name_on_bank_account"
    t.string "bank_routing_number"
    t.string "bank_account_number"
    t.string "primary_instrument"
    t.string "secondary_instrument"
    t.string "tertiary_instrument"
    t.text "song_list"
    t.string "has_car"
    t.string "has_sound_system"
    t.string "has_lighting_system"
    t.string "has_battery_generator"
    t.string "will_play_fever_events"
    t.string "will_play_wedding_receptions"
    t.string "will_play_ceremonies"
    t.string "will_travel_overnight"
    t.string "will_travel_international"
    t.string "can_emcee"
    t.string "can_lead_band"
    t.string "meal_preference"
    t.string "passport_number"
    t.string "passport_expiration"
    t.string "passport_date_issued"
    t.string "passport_first_name"
    t.string "passport_last_name"
    t.string "passport_birth_date"
    t.string "passport_city_of_birth"
    t.string "passport_state_of_birth"
    t.string "passport_country_of_birth"
    t.string "passport_nationality"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "event_id"
    t.index ["event_id"], name: "index_users_on_event_id"
  end

  create_table "users_to_events", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_foreign_key "events", "users"
  add_foreign_key "users", "events"
end
