class CreateEvents < ActiveRecord::Migration[7.0]
  def change
    create_table :events do |t|
      t.string :band_area
      t.string :producer
      t.string :primary_contact_first_name
      t.string :primary_contact_last_name
      t.string :primary_contact_email
      t.string :primary_contact_phone
      t.string :primary_contact_address1
      t.string :primary_contact_address2
      t.string :primary_contact_city
      t.string :primary_contact_state
      t.string :primary_contact_zip
      t.string :primary_contact_country
      t.string :primary_contact_role
      t.string :secondary_contact_first_name
      t.string :secondary_contact_last_name
      t.string :secondary_contact_email
      t.string :secondary_contact_phone
      t.string :secondary_contact_address1
      t.string :secondary_contact_address2
      t.string :secondary_contact_city
      t.string :secondary_contact_state
      t.string :secondary_contact_zip
      t.string :secondary_contact_country
      t.string :secondary_contact_role
      t.string :tertiary_contact_first_name
      t.string :tertiary_contact_last_name
      t.string :tertiary_contact_email
      t.string :tertiary_contact_phone
      t.string :tertiary_contact_address1
      t.string :tertiary_contact_address2
      t.string :tertiary_contact_city
      t.string :tertiary_contact_state
      t.string :tertiary_contact_zip
      t.string :tertiary_contact_country
      t.string :tertiary_contact_role
      t.datetime :event_date
      t.string :event_type
      t.string :event_status
      t.string :event_guest_count
      t.text :event_schedule
      t.string :event_load_in_time
      t.string :event_soundcheck_time_start
      t.string :event_soundcheck_time_end
      t.string :event_start_time
      t.string :set_1_start_time
      t.string :set_1_end_time
      t.string :set_2_start_time
      t.string :set_2_end_time
      t.string :set_3_start_time
      t.string :set_3_end_time
      t.string :set_4_start_time
      t.string :set_4_end_time
      t.string :event_end_time
      t.string :venue_name
      t.string :venue_phone
      t.string :venue_email
      t.string :venue_website
      t.string :venue_address1
      t.string :venue_address2
      t.string :venue_city
      t.string :venue_state
      t.string :venue_zip
      t.string :venue_country
      t.string :band_size
      t.string :band_attire
      t.string :musician_01
      t.string :musician_02
      t.string :musician_03
      t.string :musician_04
      t.string :musician_05
      t.string :musician_06
      t.string :musician_07
      t.string :musician_08
      t.string :musician_09
      t.string :musician_10
      t.string :musician_11
      t.string :musician_12
      t.string :musician_13
      t.string :musician_14
      t.string :musician_15
      t.string :musician_16
      t.string :musician_17
      t.string :musician_18
      t.string :musician_19
      t.string :musician_20
      t.string :musician_01_pay_rate
      t.string :musician_02_pay_rate
      t.string :musician_03_pay_rate
      t.string :musician_04_pay_rate
      t.string :musician_05_pay_rate
      t.string :musician_06_pay_rate
      t.string :musician_07_pay_rate
      t.string :musician_08_pay_rate
      t.string :musician_09_pay_rate
      t.string :musician_10_pay_rate
      t.string :musician_11_pay_rate
      t.string :musician_12_pay_rate
      t.string :musician_13_pay_rate
      t.string :musician_14_pay_rate
      t.string :musician_15_pay_rate
      t.string :musician_16_pay_rate
      t.string :musician_17_pay_rate
      t.string :musician_18_pay_rate
      t.string :musician_19_pay_rate
      t.string :musician_20_pay_rate
      t.string :musician_01_invited
      t.string :musician_02_invited
      t.string :musician_03_invited
      t.string :musician_04_invited
      t.string :musician_05_invited
      t.string :musician_06_invited
      t.string :musician_07_invited
      t.string :musician_08_invited
      t.string :musician_09_invited
      t.string :musician_10_invited
      t.string :musician_11_invited
      t.string :musician_12_invited
      t.string :musician_13_invited
      t.string :musician_14_invited
      t.string :musician_15_invited
      t.string :musician_16_invited
      t.string :musician_17_invited
      t.string :musician_18_invited
      t.string :musician_19_invited
      t.string :musician_20_invited
      t.string :musician_01_accepted
      t.string :musician_02_accepted
      t.string :musician_03_accepted
      t.string :musician_04_accepted
      t.string :musician_05_accepted
      t.string :musician_06_accepted
      t.string :musician_07_accepted
      t.string :musician_08_accepted
      t.string :musician_09_accepted
      t.string :musician_10_accepted
      t.string :musician_11_accepted
      t.string :musician_12_accepted
      t.string :musician_13_accepted
      t.string :musician_14_accepted
      t.string :musician_15_accepted
      t.string :musician_16_accepted
      t.string :musician_17_accepted
      t.string :musician_18_accepted
      t.string :musician_19_accepted
      t.string :musician_20_accepted
      t.text :client_notes
      t.text :special_requests
      t.text :staff_notes
      t.text :finances_formal_quote
      t.string :finances_total_price
      t.string :finances_commission1
      t.string :finances_commission2

      t.timestamps
    end
  end
end
